-- Códigos IPAS usados pelo sistema moderno do INPI (substitui os códigos numéricos antigos)
INSERT INTO despacho_codigos (codigo, descricao, categoria) VALUES
  ('IPAS001', 'Protocolo de pedido de registro de marca', 'deposito'),
  ('IPAS002', 'Pedido de registro de marca em exame', 'deposito'),
  ('IPAS003', 'Exigência formulada ao pedido de registro', 'deposito'),
  ('IPAS004', 'Resposta à exigência apresentada', 'deposito'),
  ('IPAS005', 'Exigência não respondida — pedido arquivado', 'deposito'),
  ('IPAS006', 'Pedido de registro considerado inexistente', 'deposito'),
  ('IPAS007', 'Pedido de registro em análise de mérito', 'deposito'),
  ('IPAS008', 'Pedido de registro aprovado no exame de mérito', 'deposito'),
  ('IPAS009', 'Publicação de pedido de registro para oposição (exame formal concluído)', 'publicacao'),
  ('IPAS010', 'Oposição ao pedido de registro apresentada', 'publicacao'),
  ('IPAS011', 'Notificação de oposição ao depositante', 'publicacao'),
  ('IPAS012', 'Manifestação à oposição apresentada', 'publicacao'),
  ('IPAS013', 'Prazo de oposição encerrado sem manifestação', 'publicacao'),
  ('IPAS014', 'Oposição analisada — pedido deferido', 'exame'),
  ('IPAS015', 'Oposição analisada — pedido indeferido', 'exame'),
  ('IPAS016', 'Pedido de registro deferido', 'exame'),
  ('IPAS017', 'Pedido de registro indeferido', 'exame'),
  ('IPAS018', 'Pedido de registro indeferido por colidência', 'exame'),
  ('IPAS019', 'Pedido de registro sobrestado', 'exame'),
  ('IPAS020', 'Sobrestamento encerrado', 'exame'),
  ('IPAS021', 'Recurso ao indeferimento interposto', 'recurso'),
  ('IPAS022', 'Recurso ao indeferimento não recebido', 'recurso'),
  ('IPAS023', 'Recurso ao indeferimento recebido', 'recurso'),
  ('IPAS024', 'Indeferimento do pedido', 'exame'),
  ('IPAS025', 'Recurso provido — pedido deferido', 'recurso'),
  ('IPAS026', 'Recurso denegado — indeferimento mantido', 'recurso'),
  ('IPAS027', 'Recurso provido parcialmente', 'recurso'),
  ('IPAS028', 'Recurso encaminhado ao CGIPC', 'recurso'),
  ('IPAS029', 'Concessão de registro de marca', 'concessao'),
  ('IPAS030', 'Concessão de registro com limitação', 'concessao'),
  ('IPAS031', 'Certificado de registro expedido', 'concessao'),
  ('IPAS032', 'Segunda via do certificado expedida', 'concessao'),
  ('IPAS033', 'Pedido de renovação de registro', 'renovacao'),
  ('IPAS034', 'Renovação de registro concedida', 'renovacao'),
  ('IPAS035', 'Renovação de registro indeferida', 'renovacao'),
  ('IPAS036', 'Recurso de renovação interposto', 'renovacao'),
  ('IPAS037', 'Recurso de renovação provido', 'renovacao'),
  ('IPAS038', 'Recurso de renovação denegado', 'renovacao'),
  ('IPAS039', 'Prazo de renovação em sobrestamento', 'renovacao'),
  ('IPAS040', 'Notificação para renovação', 'renovacao'),
  ('IPAS041', 'Registro extinto por não renovação', 'extincao'),
  ('IPAS042', 'Registro extinto por desistência', 'extincao'),
  ('IPAS043', 'Extinção do registro', 'extincao'),
  ('IPAS044', 'Pedido de caducidade apresentado', 'extincao'),
  ('IPAS045', 'Caducidade declarada', 'extincao'),
  ('IPAS046', 'Caducidade não declarada', 'extincao'),
  ('IPAS047', 'Decisão de considerar pedido inexistente por falta de pagamento', 'deposito'),
  ('IPAS048', 'Recurso de caducidade interposto', 'recurso'),
  ('IPAS049', 'Nulidade administrativa instaurada', 'nulidade'),
  ('IPAS050', 'Nulidade declarada', 'nulidade'),
  ('IPAS051', 'Nulidade não declarada', 'nulidade'),
  ('IPAS052', 'Recurso de nulidade interposto', 'nulidade'),
  ('IPAS053', 'Recurso de nulidade provido', 'nulidade'),
  ('IPAS054', 'Recurso de nulidade denegado', 'nulidade'),
  ('IPAS055', 'Cessão de titularidade anotada', 'anotacao'),
  ('IPAS056', 'Mudança de nome/razão social anotada', 'anotacao'),
  ('IPAS057', 'Alteração de endereço anotada', 'anotacao'),
  ('IPAS058', 'Licença de uso anotada', 'anotacao'),
  ('IPAS059', 'Cancelamento de licença anotada', 'anotacao'),
  ('IPAS060', 'Anotação de ônus/gravame', 'anotacao'),
  ('IPAS100', 'Pagamento de anuidade efetuado', 'deposito'),
  ('IPAS101', 'Anuidade em atraso — notificação', 'deposito'),
  ('IPAS102', 'Falta de pagamento de anuidade — arquivamento', 'extincao'),
  ('IPAS157', 'Arquivamento definitivo de pedido de registro por falta de pagamento da concessão', 'extincao'),
  ('IPAS158', 'Concessão de registro', 'concessao'),
  ('IPAS161', 'Arquivamento do pedido', 'exame'),
  ('IPAS235', 'Pedido de registro arquivado', 'exame'),
  ('IPAS270', 'Deferimento da petição', 'anotacao'),
  ('IPAS360', 'Registro renovado', 'renovacao'),
  ('IPAS423', 'Notificação de oposição', 'publicacao')
ON CONFLICT (codigo) DO NOTHING;
