-- Códigos de despacho ausentes encontrados na base de dados
-- Afetavam 1,1 milhão de registros sem despacho_categoria (caindo em 'analise')
-- Inclui: códigos numéricos antigos do INPI, códigos IPAS adicionais e códigos do sistema de Madri

INSERT INTO despacho_codigos (codigo, descricao, categoria) VALUES

  -- ─── CÓDIGOS NUMÉRICOS ANTIGOS (sistema pré-IPAS) ────────────────────────────
  -- Extinção / Arquivamento
  ('150',  'Despacho de extinção/arquivamento (Art. 159/162/216 LPI)',          'extincao'),
  ('700',  'Extinção do registro por caducidade (Art. 142 LPI)',                 'extincao'),
  ('660',  'Exame de caducidade por falta de uso (Art. 143 LPI)',                'extincao'),
  ('670',  'Caducidade declarada por falta de comprovação de uso',               'extincao'),
  ('692',  'Caducidade declarada por falta de comprovação com cores',            'extincao'),
  ('725',  'Arquivamento definitivo por não cumprimento de exigência',           'extincao'),
  ('730',  'Arquivamento definitivo por não cumprimento de exigência',           'extincao'),
  ('736',  'Extinção por desistência (Art. 216 LPI)',                            'extincao'),
  ('787',  'Cancelamento mantido — sem recurso interposto',                      'extincao'),
  ('860',  'Extinção por caducidade (Art. 142 LPI)',                             'extincao'),
  ('870',  'Extinção por caducidade — pedido prejudicado',                       'extincao'),
  ('895',  'Cancelamento definitivo por ausência de recurso',                    'extincao'),
  ('900',  'Caducidade declarada por falta de uso efetivo (Art. 143 LPI)',       'extincao'),
  ('515',  'Cancelamento do registro',                                           'extincao'),

  -- Nulidade administrativa / judicial
  ('570',  'Registro anulado por decisão judicial',                              'nulidade'),
  ('695',  'Processo de nulidade administrativa',                                'nulidade'),
  ('813',  'Revisão administrativa — registro cancelado',                        'nulidade'),
  ('820',  'Processo administrativo de nulidade — nulo o registro',              'nulidade'),
  ('821',  'Processo administrativo de nulidade',                                'nulidade'),
  ('823',  'Processo administrativo de nulidade — registros anulados',           'nulidade'),

  -- Recurso
  ('210',  'Recurso contra indeferimento — prazo para aditamento',               'recurso'),
  ('241',  'Revisão administrativa de recurso',                                  'recurso'),
  ('260',  'Recurso reformado — pedido indeferido',                              'recurso'),
  ('272',  'Recurso provido parcialmente — mantido indeferimento parcial',       'recurso'),
  ('587',  'Recurso contra cancelamento ex-officio',                             'recurso'),
  ('865',  'Recurso não provido — mantida decisão recorrida',                    'recurso'),

  -- Exame / Indeferimento
  ('145',  'Prazo de recurso encerrado sem interposição (indeferimento final)',   'exame'),
  ('090',  'Exigência de exame (cumprimento obrigatório)',                        'exame'),
  ('139',  'Pagamento da retribuição fora do prazo — pedido prejudicado',        'exame'),
  ('141',  'Exame de mérito',                                                    'exame'),
  ('143',  'Pedido considerado inexistente por pagamento fora do prazo',         'exame'),
  ('151',  'Exame internacional (Art. 233 LPI)',                                 'exame'),
  ('260',  'Recurso reformado — indeferimento',                                  'exame'),
  ('267',  'Exame de mérito',                                                    'exame'),
  ('274',  'Recurso prejudicado pelo arquivamento definitivo',                   'exame'),
  ('285',  'Indeferimento parcial (Art. 124 LPI)',                               'exame'),
  ('286',  'Sobrestamento até decisão final',                                    'exame'),
  ('512',  'Indeferimento com base no Art. 124 LPI',                             'exame'),
  ('610',  'Exigência — adequação e alteração de nome',                          'exame'),
  ('665',  'Exigência de prova de autoria de obra audiovisual',                  'exame'),
  ('822',  'Sobrestamento até decisão final de prorrogação',                     'exame'),
  ('921',  'Exame de classe',                                                    'exame'),
  ('990',  'Prazo prorrogado conforme Resolução',                                'exame'),

  -- Publicação / Oposição
  ('209',  'Prazo devolvido para manifestação à oposição',                       'publicacao'),

  -- Renovação
  ('920',  'Vigência do registro mantida — sem recurso contra cancelamento',     'renovacao'),

  -- Concessão com restrição
  ('269',  'Concessão sem direito ao uso exclusivo de termo',                    'concessao'),
  ('270',  'Concessão com restrição de uso exclusivo',                           'concessao'),
  ('276',  'Concessão com limitação de produto/serviço',                         'concessao'),

  -- Anotações e petições diversas (códigos de uso geral)
  ('002',  'Despacho de anotação (código legado)',                               'anotacao'),
  ('003',  'Petição — anotação de dados',                                        'anotacao'),
  ('004',  'Petição — retificação de dados',                                     'anotacao'),
  ('009',  'Petição — anotação de transferência ou alteração',                   'anotacao'),
  ('010',  'Petição — complementação de dados para oposição',                    'anotacao'),
  ('015',  'Exigência de documentação (entidade sem fins lucrativos)',            'anotacao'),
  ('025',  'Petição — retribuição de proteção decenal e certificado',            'anotacao'),
  ('027',  'Anotação de ofício',                                                 'anotacao'),
  ('029',  'Exigência — retribuição de alteração de nome e sede',                'anotacao'),
  ('030',  'Anotação de produto/código de classe',                               'anotacao'),
  ('032',  'Despacho de anotação',                                               'anotacao'),
  ('033',  'Alteração de classe',                                                'anotacao'),
  ('035',  'Anotação de subitem de classe',                                      'anotacao'),
  ('041',  'Anotação de uso de apelido notório',                                 'anotacao'),
  ('042',  'Petição de anotação — oposta',                                       'anotacao'),
  ('043',  'Petição de anotação — oposta',                                       'anotacao'),
  ('045',  'Anotação de transferência (ato constitutivo)',                        'anotacao'),
  ('050',  'Exigência — retribuição e documentação de microempresa',             'anotacao'),
  ('060',  'Exigência de formalização de transferência (decisão judicial)',       'anotacao'),
  ('091',  'Exigência de petição — reapresentação de procuração',                'anotacao'),
  ('096',  'Despacho de petição',                                                'anotacao'),
  ('097',  'Exigência de procuração com poderes para renunciar',                 'anotacao'),
  ('100',  'Anotação de alteração de especificação',                             'anotacao'),
  ('125',  'Anotação de transferência (Art. 134 LPI)',                           'anotacao'),
  ('185',  'Petição de desistência do pedido',                                   'anotacao'),
  ('208',  'Anotação de ônus/gravame (Art. 136 LPI)',                            'anotacao'),
  ('211',  'Indeferimento de petição de transferência',                          'anotacao'),
  ('218',  'Anotação de cancelamento de penhora (judicial)',                      'anotacao'),
  ('230',  'Anotação de alteração de sede/nome',                                 'anotacao'),
  ('235',  'Anotação de cessão',                                                 'anotacao'),
  ('242',  'Sobrestamento — transferência pendente de exame',                    'anotacao'),
  ('243',  'Anotação de abstenção de transferência (medida judicial)',            'anotacao'),
  ('251',  'Anotação de medida cautelar (judicial)',                              'anotacao'),
  ('252',  'Anotação de cancelamento de medida judicial',                        'anotacao'),
  ('277',  'Anotação de ofício',                                                 'anotacao'),
  ('295',  'Retificação de código de despacho',                                  'anotacao'),
  ('296',  'Reencaminhamento para reexame',                                      'anotacao'),
  ('351',  'Petição — desdobramento/agrupamento de processos',                   'anotacao'),
  ('353',  'Anotação de alteração de especificação',                             'anotacao'),
  ('400',  'Anotação — retirada de produtos fora da classe',                     'anotacao'),
  ('401',  'Retificação de especificação (RPI)',                                 'anotacao'),
  ('403',  'Anotação — retificação de classe',                                   'anotacao'),
  ('511',  'Anotação de transferência',                                          'anotacao'),
  ('552',  'Petição — requerimento de anotação',                                 'anotacao'),
  ('560',  'Anotação de alteração de sede',                                      'anotacao'),
  ('565',  'Anotação de titular',                                                'anotacao'),
  ('567',  'Sobrestamento por arrolamento judicial (Art. 136 LPI)',              'anotacao'),
  ('569',  'Suspensão de efeitos do registro — medida liminar judicial',         'anotacao'),
  ('576',  'Prorrogação de prazo',                                               'anotacao'),
  ('580',  'Anotação de titular',                                                'anotacao'),
  ('589',  'Petição não conhecida',                                              'anotacao'),
  ('590',  'Suspensão de registro — medida judicial',                            'anotacao'),
  ('591',  'Anotação de efeito suspensivo (agravo de instrumento)',              'anotacao'),
  ('600',  'Alteração de especificação de classe',                               'anotacao'),
  ('620',  'Anotação de transferência (cláusula contratual)',                    'anotacao'),
  ('630',  'Exigência — retribuição de alteração de sede',                       'anotacao'),
  ('690',  'Exigência de procuração com poderes para renunciar',                 'anotacao'),
  ('696',  'Despacho de anotação',                                               'anotacao'),
  ('697',  'Exigência de procuração em nome do titular do registro',             'anotacao'),
  ('698',  'Exigência de documentação de atividade no país de origem',           'anotacao'),
  ('702',  'Anotação de agrupamento de processos',                               'anotacao'),
  ('710',  'Anotação de transferência (Art. 134 LPI)',                           'anotacao'),
  ('715',  'Anotação de transferência (Art. 224 LPI)',                           'anotacao'),
  ('720',  'Petição prejudicada por carecer de objeto (extinção)',               'anotacao'),
  ('735',  'Petição prejudicada por carecer de objeto (extinção do registro)',   'anotacao'),
  ('740',  'Anotação de transferência (Art. 219 LPI — internacional)',           'anotacao'),
  ('745',  'Petição de anotação de transferência',                               'anotacao'),
  ('786',  'Retificação de transferência (RPI)',                                 'anotacao'),
  ('795',  'Retificação de data/especificação (RPI)',                            'anotacao'),
  ('796',  'Retificação — desistência de transferência',                         'anotacao'),
  ('806',  'Despacho de anotação',                                               'anotacao'),
  ('842',  'Despacho de anotação',                                               'anotacao'),
  ('845',  'Despacho de anotação',                                               'anotacao'),
  ('846',  'Retificação de código de despacho (RPI)',                            'anotacao'),
  ('847',  'Despacho de anotação',                                               'anotacao'),
  ('848',  'Anotação de despacho não publicado anteriormente',                   'anotacao'),
  ('849',  'Despacho de anotação',                                               'anotacao'),
  ('984',  'Despacho de anotação',                                               'anotacao'),
  ('991',  'Retificação de data de vigência e especificação (RPI)',              'anotacao'),
  ('992',  'Despacho de anotação',                                               'anotacao'),

  -- ─── CÓDIGOS IPAS ADICIONAIS ─────────────────────────────────────────────────
  -- Extinção / Arquivamento
  ('IPAS089',  'Exigência de pagamento (em petição)',                            'anotacao'),
  ('IPAS091',  'Decisão de considerar pedido inexistente por exigência de pagamento não cumprida', 'deposito'),
  ('IPAS106',  'Arquivamento definitivo de pedido de registro por falta de procuração',            'extincao'),
  ('IPAS112',  'Decisão de considerar pedido inexistente por exigência formal não respondida',     'deposito'),
  ('IPAS113',  'Decisão de considerar pedido inexistente por exigência formal não cumprida',       'deposito'),
  ('IPAS139',  'Arquivamento definitivo de pedido de registro por falta de cumprimento de exigência de mérito', 'extincao'),
  ('IPAS289',  'Arquivamento definitivo de pedido de registro por falta de documentos de marca de certificação', 'extincao'),
  ('IPAS291',  'Arquivamento definitivo de pedido de registro por falta de documentos de marca coletiva',        'extincao'),
  ('IPAS304',  'Extinção de registro pela caducidade',                           'extincao'),
  ('IPAS338',  'Notificação de caducidade',                                      'extincao'),
  ('IPAS404',  'Arquivamento de ofício de pedido de registro de marca',          'extincao'),
  ('IPAS409',  'Cancelamento de ofício de registro de marca',                    'extincao'),
  ('IPAS414',  'Extinção de registro pela inobservância do disposto no art. 217 da LPI', 'extincao'),
  ('IPAS669',  'Deferimento da petição de caducidade',                           'extincao'),

  -- Nulidade
  ('IPAS400',  'Notificação de instauração de processo de nulidade a requerimento', 'nulidade'),
  ('IPAS437',  'Notificação de instauração de processo de nulidade de ofício',   'nulidade'),
  ('IPAS530',  'Requerimento provido (nulo o registro)',                          'nulidade'),
  ('IPAS531',  'Requerimento provido (outros)',                                   'nulidade'),
  ('IPAS532',  'Requerimento não provido (mantida a concessão)',                  'nulidade'),
  ('IPAS533',  'Requerimento não provido (outros)',                               'nulidade'),
  ('IPAS534',  'Requerimento provido parcialmente (outros)',                      'nulidade'),

  -- Recurso
  ('IPAS135',  'Republicação de pedido (por perda da prioridade)',               'publicacao'),
  ('IPAS236',  'Notificação de novo impedimento legal em grau de recurso',       'recurso'),
  ('IPAS237',  'Recurso provido (decisão reformada para: Deferimento)',          'recurso'),
  ('IPAS238',  'Recurso provido (decisão reformada para: Deferimento parcial)',  'recurso'),
  ('IPAS369',  'Recurso provido (decisão reformada para: Indeferimento)',        'recurso'),
  ('IPAS370',  'Recurso provido (outros)',                                        'recurso'),
  ('IPAS535',  'Recurso provido parcialmente (decisão reformada para: Deferimento parcial)', 'recurso'),
  ('IPAS536',  'Recurso provido parcialmente (outros)',                           'recurso'),
  ('IPAS975',  'Recurso provido com devolução dos autos para primeira instância', 'recurso'),

  -- Exame / Mérito
  ('IPAS136',  'Exigência de mérito',                                            'exame'),
  ('IPAS142',  'Sobrestamento do exame de mérito',                               'exame'),
  ('IPAS192',  'Exigência de conformidade',                                      'exame'),
  ('IPAS227',  'Sobrestamento do exame de mérito (em petição)',                  'exame'),
  ('IPAS267',  'Exigência de mérito (em petição)',                               'exame'),
  ('IPAS362',  'Exigência sobre alto renome',                                    'exame'),
  ('IPAS395',  'Exigência de pagamento',                                         'anotacao'),
  ('IPAS499',  'Sobrestamento da instrução técnica',                             'exame'),
  ('IPAS654',  'Deferimento do pedido (em retificação)',                         'exame'),
  ('IPAS658',  'Indeferimento do pedido (em retificação)',                       'exame'),

  -- Publicação
  ('IPAS421',  'Republicação de pedido',                                         'publicacao'),

  -- Anotações diversas
  ('IPAS185',  'Arquivamento de petição por falta de procuração',               'anotacao'),
  ('IPAS271',  'Indeferimento da petição',                                       'anotacao'),
  ('IPAS337',  'Indeferimento da petição por falta de legítimo interesse',       'anotacao'),
  ('IPAS349',  'Deferimento parcial da petição',                                 'anotacao'),
  ('IPAS402',  'Anulação de despacho (em processo)',                             'anotacao'),
  ('IPAS403',  'Anulação de despacho (em petição)',                              'anotacao'),
  ('IPAS413',  'Despacho de petição',                                            'anotacao'),
  ('IPAS416',  'Decisão de prejudicar petição por falta de objeto',              'anotacao'),
  ('IPAS428',  'Decisão de não conhecer da petição',                             'anotacao'),
  ('IPAS462',  'Publicação de notificação judicial',                             'anotacao'),
  ('IPAS523',  'Emissão de Certidão de andamento',                               'anotacao'),
  ('IPAS566',  'Petição de retificação atendida',                                'anotacao'),
  ('IPAS567',  'Petição de retificação não atendida',                            'anotacao'),
  ('IPAS575',  'Emissão de Cópia oficial de registro de marca',                  'anotacao'),
  ('IPAS576',  'Emissão de Cópia oficial de pedido de registro',                 'anotacao'),
  ('IPAS577',  'Emissão de folha de rosto de cópia reprográfica simples',        'anotacao'),
  ('IPAS578',  'Emissão de folha de rosto de cópia reprográfica autenticada',    'anotacao'),
  ('IPAS579',  'Emissão de segunda via de certificado de registro',              'anotacao'),
  ('IPAS639',  'Publicação de decisão judicial transitada em julgado',           'anotacao'),
  ('IPAS699',  'Ato de prejudicar petição',                                      'anotacao'),
  ('IPAS1054', 'Petição de trâmite prioritário atendida',                        'anotacao'),
  ('IPAS1055', 'Petição de trâmite prioritário não atendida',                    'anotacao'),
  ('IPAS1069', 'Petição de trâmite prioritário apta (aguardando término de prazo legal)', 'anotacao'),

  -- ─── SISTEMA DE MADRI (Registro Internacional de Marcas) ─────────────────────
  -- Concessão
  ('IPAS768',  'Deferimento de designação (Madri)',                              'concessao'),
  ('IPAS770',  'Concessão de registro em designação (Madri)',                    'concessao'),
  ('IPAS781',  'Deferimento parcial de designação (Madri)',                      'concessao'),

  -- Extinção
  ('IPAS755',  'Arquivamento definitivo de designação por falta de docs. de marca coletiva ou de certificação', 'extincao'),
  ('IPAS773',  'Arquivamento definitivo de designação por falta de cumprimento de exigência de mérito', 'extincao'),
  ('IPAS780',  'Arquivamento definitivo de designação por falta de pagamento da segunda parte da retribuição', 'extincao'),
  ('IPAS963',  'Renúncia total a registro de marca em razão de cancelamento da Inscrição Internacional', 'extincao'),
  ('IPAS964',  'Desistência total de designação em razão de cancelamento da Inscrição Internacional', 'extincao'),
  ('IPAS965',  'Renúncia total a registro de marca em razão de renúncia à Inscrição Internacional que afeta o Brasil', 'extincao'),
  ('IPAS966',  'Desistência total de designação em razão de renúncia à Inscrição Internacional que afeta o Brasil', 'extincao'),

  -- Exame (Madri)
  ('IPAS771',  'Sobrestamento do exame de mérito de designação (Madri)',         'exame'),
  ('IPAS772',  'Exigência de mérito em designação (Madri)',                      'exame'),
  ('IPAS774',  'Indeferimento de designação (Madri)',                            'exame'),
  ('IPAS775',  'Indeferimento de designação em retificação (Madri)',             'exame'),
  ('IPAS794',  'Decisão de considerar Pedido Internacional inexistente por não cumprir requisitos de certificação', 'deposito'),

  -- Depósito / Protocolo (Madri)
  ('IPAS790',  'Decisão de considerar Pedido Internacional inexistente pela não resposta à notif. de inconsistência', 'deposito'),
  ('IPAS791',  'Notificação de inconsistência em Pedido Internacional',          'deposito'),
  ('IPAS797',  'Pedido Internacional certificado e enviado à Secretaria Internacional', 'deposito'),
  ('IPAS831',  'Decisão de considerar Pedido Internacional inexistente por falta de pagamento', 'deposito'),

  -- Publicação (Madri)
  ('IPAS756',  'Publicação de pedido de registro para oposição — exame formal de designação concluído (Madri)', 'publicacao'),
  ('IPAS757',  'Republicação de designação (Madri)',                             'publicacao'),

  -- Renovação (Madri)
  ('IPAS782',  'Notificação de prazo para pagamento da segunda parte da retribuição relativa a designação (Madri)', 'renovacao'),

  -- Anotações (Madri)
  ('IPAS753',  'Notificação de obrigatoriedade de apresentação de documentos de marca coletiva ou de certificação (Madri)', 'anotacao'),
  ('IPAS815',  'Comunicação ao usuário de irregularidade notificada pela SI (Madri)', 'anotacao'),
  ('IPAS820',  'Irregularidade respondida à Secretaria Internacional (Madri)',   'anotacao'),
  ('IPAS900',  'Anotação de alteração de nome e/ou endereço em designação (Madri)', 'anotacao'),
  ('IPAS901',  'Anotação de transferência de titularidade em designação (Madri)', 'anotacao'),
  ('IPAS902',  'Anotação de cancelamento parcial de especificação em designação (Madri)', 'anotacao'),
  ('IPAS903',  'Retificação de dados em designação (Madri)',                     'anotacao'),
  ('IPAS905',  'Anotação de restrição de especificação em designação (Madri)',   'anotacao'),
  ('IPAS906',  'Indeferimento de anotação de restrição de especificação em designação (Madri)', 'anotacao'),
  ('IPAS971',  'Emissão de segunda via de certificado de registro em designação (Madri)', 'anotacao'),
  ('IPAS972',  'Anulação de despacho (em comunicação de Madri)',                 'anotacao'),
  ('IPAS973',  'Ato de prejudicar comunicação de Madri',                         'anotacao'),
  ('IPAS1016', 'Anotação de transferência parcial com efeito de arquivamento de designação ou extinção de registro (Madri)', 'anotacao'),
  ('IPAS1028', 'Notificação de processo criado por transferência parcial — registro de marca (Madri)', 'anotacao'),
  ('IPAS1030', 'Notificação de processo criado por transferência parcial — exame de recurso: indeferimento (Madri)', 'anotacao'),
  ('IPAS1045', 'Notificação de processo criado por transferência parcial — inscrição internacional (Madri)', 'anotacao')

ON CONFLICT (codigo) DO NOTHING;
